### ISSUE TITLE
Only 1 Cron is executing instead of several

### ISSUE THREAD

**Issue by vkachur** [anhldbk/swarm#14] opened 2020-03-03 17:50 UTC
Hi,
I'm trying to capture performance from 2 different crons, initialized both and passed to builder.
Sometimes when I'm exectuing tests I see both crons inside a report and can debug inside debugger and see all the things. However in some cases only one Cron is executing only, no report for other Crons and no debug.

Using python 3.6.8
Locust 0.11.0
Swarm 1.1.0

Is there something I'm doing wrong? Please help. Can provide simple example if needed. 

Btw, if that helps, I'm using ConcurrentLinkedDeque to share staff between both crons, one that makes post request and adds that to deque, and another cron that polls that obj from queue and makes delete request (nulls skipped).

**Comment by anhldbk** [comment] 2020-03-04 02:21
@vkachur Thank you for using this lib. I can't tell anything from your input above. It's better if you can show me your code (after removing things related to your business)

**Comment by vkachur** [comment] 2020-03-04 09:42
@anhldbk  nvm, it was problem in my code. After some debugging, I've fixed the root cause.

**Comment by anhldbk** [comment] 2020-03-04 11:03
@vkachur Glad to hear. So I close this issue now. Thank you!

**Closed by anhldbk** 2020-03-04 11:03 UTC

**Comment by poznas** [comment] 2020-06-09 15:49
@vkachur can you share more details about the root cause?
I encountered a similar problem, only the first declared `Cron` is executed
```java
.setCrons(new FirstCron(), new SecondCron())
```

**Comment by anhldbk** [comment] 2020-06-10 04:06
@poznas Would you mind sharing your repository?

**Comment by vkachur** [comment] 2020-06-10 07:24
Never found root cause, for some reason, when I debug it, it works, but when running it is not. 
Also, we observed that some set of crons are working fine and some aren't, we couldn't find why.
The best you can do is to implement composite pattern to workaround the problem.
